In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('/home/ayush/Desktop/DATASET/0031102-231002084531237/occurrence.txt', delimiter='\t')
pd.set_option('display.max_columns', None)

/tmp/ipykernel_9550/1915100910.py:1: DtypeWarning: Columns (82,199) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/ayush/Desktop/DATASET/0031102-231002084531237/occurrence.txt', delimiter='\t')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885595 entries, 0 to 885594
Columns: 212 entries, gbifID to eventType
dtypes: bool(2), float64(146), int64(19), object(45)
memory usage: 1.4+ GB

In [16]:
df.describe()

,gbifID,accessRights,bibliographicCitation,language,modified,references,institutionID,collectionID,datasetID,institutionCode,collectionCode,ownerInstitutionCode,informationWithheld,dataGeneralizations,dynamicProperties,occurrenceID,catalogNumber,recordNumber,recordedBy,recordedByID,individualCount,organismQuantity,sex,lifeStage,reproductiveCondition,behavior,establishmentMeans,degreeOfEstablishment,pathway,georeferenceVerificationStatus,preparations,disposition,associatedOccurrences,associatedReferences,associatedSequences,associatedTaxa,otherCatalogNumbers,occurrenceRemarks,organismName,organismScope,associatedOrganisms,previousIdentifications,organismRemarks,materialSampleID,parentEventID,fieldNumber,eventTime,startDayOfYear,endDayOfYear,year,month,day,verbatimEventDate,habitat,samplingProtocol,sampleSizeValue,sampleSizeUnit,samplingEffort,fieldNotes,eventRemarks,locationID,higherGeographyID,higherGeography,waterBody,islandGroup,island,stateProvince,county,municipality,verbatimLocality,verbatimElevation,verticalDatum,verbatimDepth,minimumDistanceAboveSurfaceInMeters,maximumDistanceAboveSurfaceInMeters,locationAccordingTo,locationRemarks,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,coordinatePrecision,pointRadiusSpatialFit,verbatimCoordinateSystem,verbatimSRS,footprintWKT,footprintSRS,footprintSpatialFit,georeferencedBy,georeferencedDate,georeferenceProtocol,georeferenceSources,georeferenceRemarks,geologicalContextID,earliestEonOrLowestEonothem,latestEonOrHighestEonothem,earliestEraOrLowestErathem,latestEraOrHighestErathem,earliestPeriodOrLowestSystem,latestPeriodOrHighestSystem,earliestEpochOrLowestSeries,latestEpochOrHighestSeries,earliestAgeOrLowestStage,latestAgeOrHighestStage,lowestBiostratigraphicZone,highestBiostratigraphicZone,lithostratigraphicTerms,group,formation,member,bed,identificationID,verbatimIdentification,identificationQualifier,typeStatus,identifiedBy,identifiedByID,dateIdentified,identificationReferences,identificationVerificationStatus,identificationRemarks,taxonID,scientificNameID,acceptedNameUsageID,parentNameUsageID,originalNameUsageID,nameAccordingToID,namePublishedInID,taxonConceptID,acceptedNameUsage,parentNameUsage,originalNameUsage,nameAccordingTo,namePublishedIn,namePublishedInYear,higherClassification,subfamily,subgenus,infragenericEpithet,infraspecificEpithet,cultivarEpithet,verbatimTaxonRank,vernacularName,nomenclaturalCode,nomenclaturalStatus,taxonRemarks,elevation,elevationAccuracy,depth,depthAccuracy,distanceFromCentroidInMeters,mediaType,taxonKey,acceptedTaxonKey,kingdomKey,phylumKey,classKey,orderKey,familyKey,genusKey,subgenusKey,speciesKey,typifiedName,relativeOrganismQuantity,projectId,eventType
count,8.855950e+05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,885595.0,0.0,0.0,0.0,0.0,0.0,0.0,8.855950e+05,0.0,0.0,0.0,0.0,885595.0,885595.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,885595.000000,885595.000000,885595.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,843385.000000,843385.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.855950e+05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,885595.000000,0.0,8.855950e+05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,323.000000,0.0,8.855950e+05,8.855950e+05,885595.0,885595.0,885595.0,8.855950e+05,8.855950e+05,8.855950e+05,0.0,8.855950e+05,0.0,0.0,0.0,0.0
mean,2.967324e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74052.0,NaN,NaN,NaN,NaN,NaN,NaN,4.331916e+06,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.329664,6.578876,15.757922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.767088,24.887746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.139439e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54973.416951,NaN,2.486059e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3108.879550,NaN,2.486059e+06,2.486059e+06,1.0,44.0,212.0,3.364414e+06,3.254256e+05,2.478447e+06,NaN,2.486059e+06,NaN,NaN,NaN,NaN
std,8.655638e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,9.345058e+05,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.761335,3.782992,8.796673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.486196,11.755182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.722608e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.783331,NaN,1.445103e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,978.242834,NaN,1.445103e+05,1.445103e+05,0.0,0.0,0.0,3.587419e+06,1.140971e+06,2.927240e+03,NaN,1.445103e+05,NaN,NaN,NaN,NaN
min,2.028713e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74052.0,NaN,NaN,NaN,NaN,NaN,NaN,3.123961e+06,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2006.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-26.458570,-16.452710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.986302e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31253.000000,NaN,2.474950e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,537.901331,NaN,2.474950e+06,2.474950e+06,1.0,44.0,212.0,8.390000e+02,2.877000e+03,2.474940e+06,NaN,2.474950e+06,NaN,NaN,NaN,NaN
25%,2.028936e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74052.0,NaN,NaN,NaN,NaN,NaN,NaN,3.346812e+06,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,3.000000,8.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.677770,20.985790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.209904e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36424.000000,NaN,2.474950e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2439.896122,NaN,2.474950e+06,2.474950e+06,1.0,44.0,212.0,1.493000e+03,2.877000e+03,2.474940e+06,NaN,2.474950e+06,NaN,NaN,NaN,NaN
50%,3.765493e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74052.0,NaN,NaN,NaN,NaN,NaN,NaN,4.976229e+06,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,7.000000,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.125890,25.966260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.646045e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62543.000000,NaN,2.480449e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2944.999154,NaN,2.480449e+06,2.480449e+06,1.0,44.0,212.0,1.493000e+03,9.289000e+03,2.480444e+06,NaN,2.480449e+06,NaN,NaN,NaN,NaN
75%,3.765717e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74052.0,NaN,NaN,NaN,NaN,NaN,NaN,5.204258e+06,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020.000000,10.000000,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.929820,31.781470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.669074e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62543.000000,NaN,2.480509e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3710.815753,NaN,2.480509e+06,2.480509e+06,1.0,44.0,212.0,7.191147e+06,9.313000e+03,2.480498e+06,NaN,2.480509e+06,NaN,NaN,NaN,NaN
max,3.765939e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74052.0,NaN,NaN,NaN,NaN,NaN,NaN,5.430947e+06,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.000000,12.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72.393330,92.442710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.691876e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85366.000000,NaN,5.229165e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4991.371509,NaN,5.229165e+06,5.229165e+06,1.0,44.0,212.0,7.191147e+06,4.408414e+06,2.481908e+06,NaN,5.229165e+06,NaN,NaN,NaN,NaN

In [6]:
df.head(7)

,gbifID,accessRights,bibliographicCitation,language,license,modified,publisher,references,rightsHolder,type,institutionID,collectionID,datasetID,institutionCode,collectionCode,datasetName,ownerInstitutionCode,basisOfRecord,informationWithheld,dataGeneralizations,dynamicProperties,occurrenceID,catalogNumber,recordNumber,recordedBy,recordedByID,individualCount,organismQuantity,organismQuantityType,sex,lifeStage,reproductiveCondition,behavior,establishmentMeans,degreeOfEstablishment,pathway,georeferenceVerificationStatus,occurrenceStatus,preparations,disposition,associatedOccurrences,associatedReferences,associatedSequences,associatedTaxa,otherCatalogNumbers,occurrenceRemarks,organismID,organismName,organismScope,associatedOrganisms,previousIdentifications,organismRemarks,materialSampleID,eventID,parentEventID,fieldNumber,eventDate,eventTime,startDayOfYear,endDayOfYear,year,month,day,verbatimEventDate,habitat,samplingProtocol,sampleSizeValue,sampleSizeUnit,samplingEffort,fieldNotes,eventRemarks,locationID,higherGeographyID,higherGeography,continent,waterBody,islandGroup,island,countryCode,stateProvince,county,municipality,locality,verbatimLocality,verbatimElevation,verticalDatum,verbatimDepth,minimumDistanceAboveSurfaceInMeters,maximumDistanceAboveSurfaceInMeters,locationAccordingTo,locationRemarks,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,coordinatePrecision,pointRadiusSpatialFit,verbatimCoordinateSystem,verbatimSRS,footprintWKT,footprintSRS,footprintSpatialFit,georeferencedBy,georeferencedDate,georeferenceProtocol,georeferenceSources,georeferenceRemarks,geologicalContextID,earliestEonOrLowestEonothem,latestEonOrHighestEonothem,earliestEraOrLowestErathem,latestEraOrHighestErathem,earliestPeriodOrLowestSystem,latestPeriodOrHighestSystem,earliestEpochOrLowestSeries,latestEpochOrHighestSeries,earliestAgeOrLowestStage,latestAgeOrHighestStage,lowestBiostratigraphicZone,highestBiostratigraphicZone,lithostratigraphicTerms,group,formation,member,bed,identificationID,verbatimIdentification,identificationQualifier,typeStatus,identifiedBy,identifiedByID,dateIdentified,identificationReferences,identificationVerificationStatus,identificationRemarks,taxonID,scientificNameID,acceptedNameUsageID,parentNameUsageID,originalNameUsageID,nameAccordingToID,namePublishedInID,taxonConceptID,scientificName,acceptedNameUsage,parentNameUsage,originalNameUsage,nameAccordingTo,namePublishedIn,namePublishedInYear,higherClassification,kingdom,phylum,class,order,family,subfamily,genus,genericName,subgenus,infragenericEpithet,specificEpithet,infraspecificEpithet,cultivarEpithet,taxonRank,verbatimTaxonRank,vernacularName,nomenclaturalCode,taxonomicStatus,nomenclaturalStatus,taxonRemarks,datasetKey,publishingCountry,lastInterpreted,elevation,elevationAccuracy,depth,depthAccuracy,distanceFromCentroidInMeters,issue,mediaType,hasCoordinate,hasGeospatialIssues,taxonKey,acceptedTaxonKey,kingdomKey,phylumKey,classKey,orderKey,familyKey,genusKey,subgenusKey,speciesKey,species,acceptedScientificName,verbatimScientificName,typifiedName,protocol,lastParsed,lastCrawled,repatriated,relativeOrganismQuantity,projectId,level0Gid,level0Name,level1Gid,level1Name,level2Gid,level2Name,level3Gid,level3Name,iucnRedListCategory,eventType
0,2028713273,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,PlutoF,NaN,Kristjan Adojaan,Event,NaN,NaN,74052,NaN,NaN,Birdmap data,NaN,MACHINE_OBSERVATION,NaN,NaN,NaN,3123967,NaN,NaN,NaN,NaN,1,1.0,individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRESENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.Maria,NaN,NaN,NaN,NaN,NaN,NaN,https://plutof.ut.ee/#/event/view/3537494,NaN,NaN,2007-08-07T06:00:00,NaN,NaN,NaN,2007,8,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EUROPE,NaN,NaN,NaN,BY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.30767,27.30983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4986308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85366,NaN,2480726,NaN,NaN,NaN,NaN,NaN,"Pandion haliaetus (Linnaeus, 1758)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Chordata,Aves,Accipitriformes,Pandionidae,NaN,Pandion,Pandion,NaN,NaN,haliaetus,NaN,NaN,SPECIES,NaN,NaN,NaN,ACCEPTED,NaN,NaN,712dba38-74cc-4704-87c0-63d1bf8484bc,EE,2023-10-17T20:02:35.641Z,NaN,NaN,NaN,NaN,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,NaN,True,False,2480726,2480726,1,44,212,7191147,4408414,2480725,NaN,2480726,Pandion haliaetus,"Pandion haliaetus (Linnaeus, 1758)","Pandion haliaetus (Linnaeus, 1758)",NaN,DWC_ARCHIVE,2023-10-17T20:02:35.641Z,2023-10-17T19:50:29.040Z,True,NaN,NaN,BLR,Belarus,BLR.1_1,Brest,BLR.1.10_1,Luninets,NaN,NaN,LC,NaN
1,2028931999,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,PlutoF,NaN,Kristjan Adojaan,Event,NaN,NaN,74052,NaN,NaN,Birdmap data,NaN,MACHINE_OBSERVATION,NaN,NaN,NaN,3338562,NaN,NaN,NaN,NaN,1,1.0,individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRESENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.Ahja5,NaN,NaN,NaN,NaN,NaN,NaN,https://plutof.ut.ee/#/event/view/3752159,NaN,NaN,2017-06-19T10:24:00,NaN,NaN,NaN,2017,6,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EUROPE,NaN,NaN,NaN,UA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.14460,34.26638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5201575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62543,NaN,2474950,NaN,NaN,NaN,NaN,NaN,"Grus grus (Linnaeus, 1758)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Chordata,Aves,Gruiformes,Gruidae,NaN,Grus,Grus,NaN,NaN,grus,NaN,NaN,SPECIES,NaN,NaN,NaN,ACCEPTED,NaN,NaN,712dba38-74cc-4704-87c0-63d1bf8484bc,EE,2023-10-17T20:04:02.378Z,NaN,NaN,NaN,NaN,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,NaN,True,False,2474950,2474950,1,44,212,1493,9313,2474940,NaN,2474950,Grus grus,"Grus grus (Linnaeus, 1758)","Grus grus (Linnaeus, 1758)",NaN,DWC_ARCHIVE,2023-10-17T20:04:02.378Z,2023-10-17T19:50:29.040Z,True,NaN,NaN,UKR,Ukraine,UKR.9_1,Kherson,UKR.9.12_1,Novotro‹ts'kyi,NaN,NaN,LC,NaN
2,2028715905,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,PlutoF,NaN,Kristjan Adojaan,Event,NaN,NaN,74052,NaN,NaN,Birdmap data,NaN,MACHINE_OBSERVATION,NaN,NaN,NaN,3123985,NaN,NaN,NaN,NaN,1,1.0,individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRESENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.Maria,NaN,NaN,NaN,NaN,NaN,NaN,https://plutof.ut.ee/#/event/view/3537512,NaN,NaN,2007-08-22T12:00:00,NaN,NaN,NaN,2007,8,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EUROPE,NaN,NaN,NaN,RO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.29900,26.57217,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4986326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85366,NaN,2480726,NaN,NaN,NaN,NaN,NaN,"Pandion haliaetus (Linnaeus, 1758)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Chordata,Aves,Accipitriformes,Pandionidae,NaN,Pandion,Pandion,NaN,NaN,haliaetus,NaN,NaN,SPECIES,NaN,NaN,NaN,ACCEPTED,NaN,NaN,712dba38-74cc-4704-87c0-63d1bf8484bc,EE,2023-10-17T20:02:37.986Z,NaN,NaN,NaN,NaN,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,NaN,True,False,2480726,2480726,1,44,212,7191147,4408414,2480725,NaN,2480726,Pandion haliaetus,"Pandion haliaetus (Linnaeus, 1758)","Pandion haliaetus (Linnaeus, 1758)",NaN,DWC_ARCHIVE,2023-10-17T20:02:37.986Z,2023-10-17T19:50:29.040Z,True,NaN,NaN,ROU,Romania,ROU.4_1,Bacău,ROU.4.80_1,Targu Ocna,NaN,NaN,LC,NaN
3,2028936907,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,PlutoF,NaN,Kristjan Adojaan,Event,NaN,NaN,74052,NaN,NaN,Birdmap data,NaN,MACHINE_OBSERVATION,NaN,NaN,NaN,3338580,NaN,NaN,NaN,NaN,1,1.0,individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRESENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.Ahja5,NaN,NaN,NaN,NaN,NaN,NaN,https://plutof.ut.ee/#/event/view/3752177,NaN,NaN,2017-06-19T16:24:00,NaN,NaN,NaN,2017,6,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EUROPE,NaN,NaN,NaN,UA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.14753,34.23717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5201593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62543,NaN,2474950,NaN,NaN,NaN,NaN,NaN,"Grus grus (Linnaeus, 1758)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Chordata,Aves,Gruiformes,Gruidae,NaN,Grus,Grus,NaN,NaN,grus,NaN,NaN,SPECIES,NaN,NaN,NaN,ACCEPTED,NaN,NaN,712dba38-74cc-4704-87c0-63d1bf8484bc,EE,2023-10-17T20:04:02.379Z,NaN,NaN,NaN,NaN,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,NaN,True,False,2474950,2474950,1,44,212,1493,9313,2474940,NaN,2474950,Grus grus,"Grus grus (Linnaeus, 1758)","Grus grus (Linnaeus, 1758)",NaN,DWC_ARCHIVE,2023-10-17T20:04:02.379Z,2023-10-17T19:50:29.040Z,True,NaN,NaN,UKR,Ukraine,UKR.9_1,Kherson,UKR.9.12_1,Novotro‹ts'kyi,NaN,NaN,LC,NaN
4,2028715906,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,PlutoF,NaN,Kristjan Adojaan,Event,NaN,NaN,74052,NaN,NaN,Birdmap data,NaN,MACHINE_OBSERVATION,NaN,NaN,NaN,3124010,NaN,NaN,NaN,NaN,1,1.0,individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRESENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.Maria,NaN,NaN,NaN,NaN,NaN,NaN,https://plutof.ut.ee/#/event/view/3537537,NaN,NaN,2007-08-26T06:00:00,NaN,NaN,NaN,2007,8,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFRICA,NaN,NaN,NaN,LY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.49767,24.46550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4986351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85366,NaN,2480726,NaN,NaN,NaN,NaN,NaN,"Pandion haliaetus (Linnaeus, 1758)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Chordata,Aves,Accipitriformes,Pandionidae,NaN,Pandion,Pandion,NaN,NaN,haliaetus,NaN,NaN,SPECIES,NaN,NaN,NaN,ACCEPTED,NaN,NaN,712dba38-74cc-4704-87c0-63d1bf8484bc,EE,2023-10-17T20:02:38.023Z,NaN,NaN,NaN,NaN,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,NaN,True,False,2480726,2480726,1,44,212,7191147,4408414,2480725,NaN,2480726,Pandion haliaetus,"Pandion haliaetus (Linnaeus, 1758)","Pandion haliaetus (Linnaeus, 1758)",NaN,DWC_ARCHIVE,2023-10-17T20:02:38.023Z,2023-10-17T19:50:29.040Z,True,NaN,NaN,LBY,Libya,LBY.1_1,Al Butnan,NaN,NaN,NaN,NaN,LC,NaN
5,2028926108,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,PlutoF,NaN,Kristjan Adojaan,Event,NaN,NaN,74052,NaN,NaN,Birdmap data,NaN,MACHINE_OBSERVATION,NaN,NaN,NaN,3338599,NaN,NaN,NaN,NaN,1,1.0,individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRESENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.Ahja5,NaN,NaN,NaN,NaN,NaN,NaN,https://plutof.ut.ee/#/event/view/3752197,NaN,NaN,2017-06-19T22:44:00,NaN,NaN,NaN,2017,6,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EUROPE,NaN,NaN,NaN,UA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.14125,34.24380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5201613,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62543,NaN,2474950,NaN,NaN,NaN,NaN,NaN,"Grus grus (Linnaeus, 1758)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Chordata,Aves,Gruiformes,Gruidae,NaN,Grus,Grus,NaN,NaN,grus,NaN,NaN,SPECIES,NaN,NaN,NaN,ACCEPTED,NaN,NaN,712dba38-74cc-4704-87c0-63d1bf8484bc,EE,2023-10-17T20:04:02.380Z,NaN,NaN,NaN,NaN,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,NaN,True,False,2474950,2474950,1,44,212,1493,9313,2474940,NaN,2474950,Grus grus,"Grus grus (Linnaeus, 1758)","Grus grus (Linnaeus, 1758)",NaN,DWC_ARCHIVE,2023-10-17T20:04:02.380Z,2023-10-17T19:50:29.040Z,True,NaN,NaN,UKR,Ukraine,UKR.9_1,Kherson,UKR.9.12_1,Novotro‹ts'kyi,NaN,NaN,LC,NaN
6,2028713670,NaN,NaN,NaN,CC_BY_NC_4_0,NaN,PlutoF,NaN,Kristjan Adojaan,Event,NaN,NaN,74052,NaN,NaN,Birdmap data,NaN,MACHINE_OBSERVATION,NaN,NaN,NaN,3124029,NaN,NaN,NaN,NaN,1,1.0,individuals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PRESENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.Maria,NaN,NaN,NaN,NaN,NaN,NaN,https://plutof.ut.ee/#/event/view/3537556,NaN,NaN,2007-08-28T16:00:00,NaN,NaN,NaN,2007,8,28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AFRICA,NaN,NaN,NaN,TD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.88700,22.85383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4986370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,85366,NaN,2480726,NaN,NaN,NaN,NaN,NaN,"Pandion haliaetus (Linnaeus, 1758)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animalia,Chordata,Aves,Accipitriformes,Pandionidae,NaN,Pandion,Pandion,NaN,NaN,haliaetus,NaN,NaN,SPECIES,NaN,NaN,NaN,ACCEPTED,NaN,NaN,712dba38-74cc-4704-87c0-63d1bf8484bc,EE,2023-10-17T20:02:38.030Z,NaN,NaN,NaN,NaN,NaN,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,NaN,True,False,2480726,2480726,1,44,212,7191147,4408414,2480725,NaN,2480726,Pandion haliaetus,"Pandion haliaetus (Linnaeus, 1758)","Pandion haliaetus (Linnaeus, 1758)",NaN,DWC_ARCHIVE,2023-10-17T20:02:38.030Z,2023-10-17T19:50:29.040Z,True,NaN,NaN,TCD,Chad,TCD.5_1,Ennedi Est,TCD.5.1_1,Ennedi Est,TCD.5.1.1_1,Ennedi Est,LC,NaN

In [18]:
for i in df.columns:
    if df[i].isnull().sum() > 500000:
        del df[i]
        print(i)

accessRights
bibliographicCitation
language
modified
references
institutionID
collectionID
institutionCode
collectionCode
ownerInstitutionCode
informationWithheld
dataGeneralizations
dynamicProperties
catalogNumber
recordNumber
recordedBy
recordedByID
sex
lifeStage
reproductiveCondition
behavior
establishmentMeans
degreeOfEstablishment
pathway
georeferenceVerificationStatus
preparations
disposition
associatedOccurrences
associatedReferences
associatedSequences
associatedTaxa
otherCatalogNumbers
occurrenceRemarks
organismName
organismScope
associatedOrganisms
previousIdentifications
organismRemarks
materialSampleID
parentEventID
fieldNumber
eventTime
startDayOfYear
endDayOfYear
verbatimEventDate
habitat
samplingProtocol
sampleSizeValue
sampleSizeUnit
samplingEffort
fieldNotes
eventRemarks
locationID
higherGeographyID
higherGeography
waterBody
islandGroup
island
stateProvince
county
municipality
verbatimLocality
verbatimElevation
verticalDatum
verbatimDepth
minimumDistanceAboveSurfaceInMeters
maximumDistanceAboveSurfaceInMeters
locationAccordingTo
locationRemarks
coordinateUncertaintyInMeters
coordinatePrecision
pointRadiusSpatialFit
verbatimCoordinateSystem
verbatimSRS
footprintWKT
footprintSRS
footprintSpatialFit
georeferencedBy
georeferencedDate
georeferenceProtocol
georeferenceSources
georeferenceRemarks
geologicalContextID
earliestEonOrLowestEonothem
latestEonOrHighestEonothem
earliestEraOrLowestErathem
latestEraOrHighestErathem
earliestPeriodOrLowestSystem
latestPeriodOrHighestSystem
earliestEpochOrLowestSeries
latestEpochOrHighestSeries
earliestAgeOrLowestStage
latestAgeOrHighestStage
lowestBiostratigraphicZone
highestBiostratigraphicZone
lithostratigraphicTerms
group
formation
member
bed
verbatimIdentification
identificationQualifier
typeStatus
identifiedBy
identifiedByID
dateIdentified
identificationReferences
identificationVerificationStatus
identificationRemarks
scientificNameID
parentNameUsageID
originalNameUsageID
nameAccordingToID
namePublishedInID
taxonConceptID
acceptedNameUsage
parentNameUsage
originalNameUsage
nameAccordingTo
namePublishedIn
namePublishedInYear
higherClassification
subfamily
subgenus
infragenericEpithet
infraspecificEpithet
cultivarEpithet
verbatimTaxonRank
vernacularName
nomenclaturalCode
nomenclaturalStatus
taxonRemarks
elevation
elevationAccuracy
depth
depthAccuracy
distanceFromCentroidInMeters
mediaType
subgenusKey
typifiedName
relativeOrganismQuantity
projectId
level3Name
eventType

In [17]:
for i in df.columns:
    if df[i].nunique() == 1:
        del df[i]
        print(i)

license
publisher
rightsHolder
type
datasetID
datasetName
basisOfRecord
individualCount
organismQuantity
organismQuantityType
occurrenceStatus
locality
kingdom
phylum
class
taxonRank
taxonomicStatus
datasetKey
publishingCountry
kingdomKey
phylumKey
classKey
protocol
lastCrawled

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885595 entries, 0 to 885594
Data columns (total 44 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   gbifID                  885595 non-null  int64
 1   occurrenceID            885595 non-null  int64
 2   organismID              885595 non-null  object
 3   eventID                 885595 non-null  object
 4   eventDate               885595 non-null  object
 5   year                    885595 non-null  int64
 6   month                   885595 non-null  int64
 7   day                     885595 non-null  int64
 8   continent               849534 non-null  object
 9   countryCode             849714 non-null  object
 10  decimalLatitude         843385 non-null  float64
 11  decimalLongitude        843385 non-null  float64
 12  identificationID        885595 non-null  int64
 13  taxonID                 885595 non-null  int64
 14  acceptedNameUsageID     885595 non-null  int64
 15  scientificName          885595 non-null  object
 16  order                   885595 non-null  object
 17  family                  885595 non-null  object
 18  genus                   885595 non-null  object
 19  genericName             885595 non-null  object
 20  specificEpithet         885595 non-null  object
 21  lastInterpreted         885595 non-null  object
 22  issue                   885595 non-null  object
 23  hasCoordinate           885595 non-null  bool
 24  hasGeospatialIssues     885595 non-null  bool
 25  taxonKey                885595 non-null  int64
 26  acceptedTaxonKey        885595 non-null  int64
 27  orderKey                885595 non-null  int64
 28  familyKey               885595 non-null  int64
 29  genusKey                885595 non-null  int64
 30  speciesKey              885595 non-null  int64
 31  species                 885595 non-null  object
 32  acceptedScientificName  885595 non-null  object
 33  verbatimScientificName  885595 non-null  object
 34  lastParsed              885595 non-null  object
 35  repatriated             851240 non-null  object
 36  level0Gid               833267 non-null  object
 37  level0Name              833267 non-null  object
 38  level1Gid               833267 non-null  object
 39  level1Name              833267 non-null  object
 40  level2Gid               812053 non-null  object
 41  level2Name              812053 non-null  object
 42  level3Gid               402004 non-null  object
 43  iucnRedListCategory     885595 non-null  object
dtypes: bool(2), float64(2), int64(14), object(26)
memory usage: 285.5+ MB

In [20]:
df.head()

,gbifID,occurrenceID,organismID,eventID,eventDate,year,month,day,continent,countryCode,decimalLatitude,decimalLongitude,identificationID,taxonID,acceptedNameUsageID,scientificName,order,family,genus,genericName,specificEpithet,lastInterpreted,issue,hasCoordinate,hasGeospatialIssues,taxonKey,acceptedTaxonKey,orderKey,familyKey,genusKey,speciesKey,species,acceptedScientificName,verbatimScientificName,lastParsed,repatriated,level0Gid,level0Name,level1Gid,level1Name,level2Gid,level2Name,level3Gid,iucnRedListCategory
0,2028713273,3123967,2.Maria,https://plutof.ut.ee/#/event/view/3537494,2007-08-07T06:00:00,2007,8,7,EUROPE,BY,52.30767,27.30983,4986308,85366,2480726,"Pandion haliaetus (Linnaeus, 1758)",Accipitriformes,Pandionidae,Pandion,Pandion,haliaetus,2023-10-17T20:02:35.641Z,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,True,False,2480726,2480726,7191147,4408414,2480725,2480726,Pandion haliaetus,"Pandion haliaetus (Linnaeus, 1758)","Pandion haliaetus (Linnaeus, 1758)",2023-10-17T20:02:35.641Z,True,BLR,Belarus,BLR.1_1,Brest,BLR.1.10_1,Luninets,NaN,LC
1,2028931999,3338562,111.Ahja5,https://plutof.ut.ee/#/event/view/3752159,2017-06-19T10:24:00,2017,6,19,EUROPE,UA,46.14460,34.26638,5201575,62543,2474950,"Grus grus (Linnaeus, 1758)",Gruiformes,Gruidae,Grus,Grus,grus,2023-10-17T20:04:02.378Z,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,True,False,2474950,2474950,1493,9313,2474940,2474950,Grus grus,"Grus grus (Linnaeus, 1758)","Grus grus (Linnaeus, 1758)",2023-10-17T20:04:02.378Z,True,UKR,Ukraine,UKR.9_1,Kherson,UKR.9.12_1,Novotro‹ts'kyi,NaN,LC
2,2028715905,3123985,2.Maria,https://plutof.ut.ee/#/event/view/3537512,2007-08-22T12:00:00,2007,8,22,EUROPE,RO,46.29900,26.57217,4986326,85366,2480726,"Pandion haliaetus (Linnaeus, 1758)",Accipitriformes,Pandionidae,Pandion,Pandion,haliaetus,2023-10-17T20:02:37.986Z,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,True,False,2480726,2480726,7191147,4408414,2480725,2480726,Pandion haliaetus,"Pandion haliaetus (Linnaeus, 1758)","Pandion haliaetus (Linnaeus, 1758)",2023-10-17T20:02:37.986Z,True,ROU,Romania,ROU.4_1,Bacău,ROU.4.80_1,Targu Ocna,NaN,LC
3,2028936907,3338580,111.Ahja5,https://plutof.ut.ee/#/event/view/3752177,2017-06-19T16:24:00,2017,6,19,EUROPE,UA,46.14753,34.23717,5201593,62543,2474950,"Grus grus (Linnaeus, 1758)",Gruiformes,Gruidae,Grus,Grus,grus,2023-10-17T20:04:02.379Z,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,True,False,2474950,2474950,1493,9313,2474940,2474950,Grus grus,"Grus grus (Linnaeus, 1758)","Grus grus (Linnaeus, 1758)",2023-10-17T20:04:02.379Z,True,UKR,Ukraine,UKR.9_1,Kherson,UKR.9.12_1,Novotro‹ts'kyi,NaN,LC
4,2028715906,3124010,2.Maria,https://plutof.ut.ee/#/event/view/3537537,2007-08-26T06:00:00,2007,8,26,AFRICA,LY,29.49767,24.46550,4986351,85366,2480726,"Pandion haliaetus (Linnaeus, 1758)",Accipitriformes,Pandionidae,Pandion,Pandion,haliaetus,2023-10-17T20:02:38.023Z,CONTINENT_DERIVED_FROM_COORDINATES;TAXON_MATCH...,True,False,2480726,2480726,7191147,4408414,2480725,2480726,Pandion haliaetus,"Pandion haliaetus (Linnaeus, 1758)","Pandion haliaetus (Linnaeus, 1758)",2023-10-17T20:02:38.023Z,True,LBY,Libya,LBY.1_1,Al Butnan,NaN,NaN,NaN,LC

In [27]:

df.isnull().sum()

gbifID                         0
occurrenceID                   0
organismID                     0
eventID                        0
eventDate                      0
year                           0
month                          0
day                            0
continent                  36061
countryCode                35881
decimalLatitude            42210
decimalLongitude           42210
identificationID               0
taxonID                        0
acceptedNameUsageID            0
scientificName                 0
order                          0
family                         0
genus                          0
genericName                    0
specificEpithet                0
lastInterpreted                0
issue                          0
hasCoordinate                  0
hasGeospatialIssues            0
taxonKey                       0
acceptedTaxonKey               0
orderKey                       0
familyKey                      0
genusKey                       0
speciesKey                     0
species                        0
acceptedScientificName         0
verbatimScientificName         0
lastParsed                     0
repatriated                34355
level0Gid                  52328
level0Name                 52328
level1Gid                  52328
level1Name                 52328
level2Gid                  73542
level2Name                 73542
level3Gid                 483591
iucnRedListCategory            0
dtype: int64

In [33]:
df.drop("level3Gid", axis =1,inplace=True)

In [39]:
select_list = ["eventDate","continent","scientificName","genericName","species","level0Name","level1Name","level2Name"]

In [40]:
df["level1Name"]

0             Brest
1           Kherson
2             Bacău
3           Kherson
4         Al Butnan
            ...
885590      Kherson
885591      Kherson
885592      Kherson
885593      Kherson
885594      Kherson
Name: level1Name, Length: 885595, dtype: object

In [41]:
df["level2Name"]

0               Luninets
1         Novotro‹ts'kyi
2             Targu Ocna
3         Novotro‹ts'kyi
4                    NaN
               ...
885590    Novotro‹ts'kyi
885591    Novotro‹ts'kyi
885592    Novotro‹ts'kyi
885593    Novotro‹ts'kyi
885594    Novotro‹ts'kyi
Name: level2Name, Length: 885595, dtype: object

In [42]:
df[select_list]

,eventDate,continent,scientificName,genericName,species,level0Name,level1Name,level2Name
0,2007-08-07T06:00:00,EUROPE,"Pandion haliaetus (Linnaeus, 1758)",Pandion,Pandion haliaetus,Belarus,Brest,Luninets
1,2017-06-19T10:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
2,2007-08-22T12:00:00,EUROPE,"Pandion haliaetus (Linnaeus, 1758)",Pandion,Pandion haliaetus,Romania,Bacău,Targu Ocna
3,2017-06-19T16:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
4,2007-08-26T06:00:00,AFRICA,"Pandion haliaetus (Linnaeus, 1758)",Pandion,Pandion haliaetus,Libya,Al Butnan,NaN
...,...,...,...,...,...,...,...,...
885590,2017-06-18T02:25:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
885591,2017-06-18T08:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
885592,2017-06-18T17:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
885593,2017-06-18T23:25:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
885594,2017-06-19T04:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi

In [43]:
df_select_cols = df[select_list].copy()

In [44]:
df_select_cols.shape

(885595, 8)

In [57]:
df_select_cols.rename(
    columns=
    {
        "level0Name":"Country",
        "level1Name":"City",
        "level2Name":"Town"}

    ,
    inplace =True
)

In [58]:
df["species"].unique()

array(['Pandion haliaetus', 'Grus grus', 'Ciconia nigra',
       'Haliaeetus albicilla', 'Aquila clanga', 'Aquila pomarina',
       'Buteo buteo', 'Ciconia ciconia', 'Botaurus stellaris',
       'Aegypius monachus'], dtype=object)

In [59]:
df_select_cols

,eventDate,continent,scientificName,genericName,species,Country,City,Town
0,2007-08-07T06:00:00,EUROPE,"Pandion haliaetus (Linnaeus, 1758)",Pandion,Pandion haliaetus,Belarus,Brest,Luninets
1,2017-06-19T10:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
2,2007-08-22T12:00:00,EUROPE,"Pandion haliaetus (Linnaeus, 1758)",Pandion,Pandion haliaetus,Romania,Bacău,Targu Ocna
3,2017-06-19T16:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
4,2007-08-26T06:00:00,AFRICA,"Pandion haliaetus (Linnaeus, 1758)",Pandion,Pandion haliaetus,Libya,Al Butnan,NaN
...,...,...,...,...,...,...,...,...
885590,2017-06-18T02:25:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
885591,2017-06-18T08:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
885592,2017-06-18T17:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
885593,2017-06-18T23:25:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi
885594,2017-06-19T04:24:00,EUROPE,"Grus grus (Linnaeus, 1758)",Grus,Grus grus,Ukraine,Kherson,Novotro‹ts'kyi

In [63]:
df_select_cols["City"].nunique()

1110